// flow-typed signature: 2e02e70b26a8d41481385b3bfa7e7a7e
// flow-typed version: <<STUB>>/@fortawesome/pro-duotone-svg-icons_v5.14.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/pro-duotone-svg-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/pro-duotone-svg-icons' {
  declare module.exports: any;
}
