// flow-typed signature: 75d27bac25724021051bbed1b1e618fc
// flow-typed version: <<STUB>>/lattice_v0.60.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice' {
  declare module.exports: any;
}
