// flow-typed signature: be7990560de2e401f358938964bd25ad
// flow-typed version: <<STUB>>/lattice_v^0.29.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lattice/build/lattice' {
  declare module.exports: any;
}

declare module 'lattice/build/lattice.min' {
  declare module.exports: any;
}

declare module 'lattice/config/env' {
  declare module.exports: any;
}

declare module 'lattice/config/flow/types' {
  declare module.exports: any;
}

declare module 'lattice/config/karma/karma.config.babel' {
  declare module.exports: any;
}

declare module 'lattice/config/karma/karma.config.base' {
  declare module.exports: any;
}

declare module 'lattice/config/karma/karma.config' {
  declare module.exports: any;
}

declare module 'lattice/config/lib.config' {
  declare module.exports: any;
}

declare module 'lattice/config/lib.paths' {
  declare module.exports: any;
}

declare module 'lattice/config/webpack/webpack.config.babel' {
  declare module.exports: any;
}

declare module 'lattice/src/api/AnalysisApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/AuthorizationApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/DataApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/DataSourcesApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/EntityDataModelApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/LinkingApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/OrganizationsApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/PermissionsApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/PrincipalsApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/RequestsApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/SearchApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/SyncApi' {
  declare module.exports: any;
}

declare module 'lattice/src/config/Configuration' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/ApiNames' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/ApiPaths' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/EnvToUrlMap' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/ActionTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/index' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/PermissionTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/PrincipalTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/RequestStateTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/SecurableTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/index' {
  declare module.exports: any;
}

declare module 'lattice/src/models/AccessCheck' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Ace' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Acl' {
  declare module.exports: any;
}

declare module 'lattice/src/models/AclData' {
  declare module.exports: any;
}

declare module 'lattice/src/models/DataSource' {
  declare module.exports: any;
}

declare module 'lattice/src/models/EntitySet' {
  declare module.exports: any;
}

declare module 'lattice/src/models/EntityType' {
  declare module.exports: any;
}

declare module 'lattice/src/models/FullyQualifiedName' {
  declare module.exports: any;
}

declare module 'lattice/src/models/index' {
  declare module.exports: any;
}

declare module 'lattice/src/models/LinkingEntitySet' {
  declare module.exports: any;
}

declare module 'lattice/src/models/LinkingEntityType' {
  declare module.exports: any;
}

declare module 'lattice/src/models/LinkingRequest' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Organization' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Principal' {
  declare module.exports: any;
}

declare module 'lattice/src/models/PropertyType' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Request' {
  declare module.exports: any;
}

declare module 'lattice/src/models/RequestStatus' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Role' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Schema' {
  declare module.exports: any;
}

declare module 'lattice/src/models/template' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/AxiosUtils' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/LangUtils' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/Logger' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/ValidationUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lattice/build/lattice.js' {
  declare module.exports: $Exports<'lattice/build/lattice'>;
}
declare module 'lattice/build/lattice.min.js' {
  declare module.exports: $Exports<'lattice/build/lattice.min'>;
}
declare module 'lattice/config/env.js' {
  declare module.exports: $Exports<'lattice/config/env'>;
}
declare module 'lattice/config/flow/types.js' {
  declare module.exports: $Exports<'lattice/config/flow/types'>;
}
declare module 'lattice/config/karma/karma.config.babel.js' {
  declare module.exports: $Exports<'lattice/config/karma/karma.config.babel'>;
}
declare module 'lattice/config/karma/karma.config.base.js' {
  declare module.exports: $Exports<'lattice/config/karma/karma.config.base'>;
}
declare module 'lattice/config/karma/karma.config.js' {
  declare module.exports: $Exports<'lattice/config/karma/karma.config'>;
}
declare module 'lattice/config/lib.config.js' {
  declare module.exports: $Exports<'lattice/config/lib.config'>;
}
declare module 'lattice/config/lib.paths.js' {
  declare module.exports: $Exports<'lattice/config/lib.paths'>;
}
declare module 'lattice/config/webpack/webpack.config.babel.js' {
  declare module.exports: $Exports<'lattice/config/webpack/webpack.config.babel'>;
}
declare module 'lattice/src/api/AnalysisApi.js' {
  declare module.exports: $Exports<'lattice/src/api/AnalysisApi'>;
}
declare module 'lattice/src/api/AuthorizationApi.js' {
  declare module.exports: $Exports<'lattice/src/api/AuthorizationApi'>;
}
declare module 'lattice/src/api/DataApi.js' {
  declare module.exports: $Exports<'lattice/src/api/DataApi'>;
}
declare module 'lattice/src/api/DataSourcesApi.js' {
  declare module.exports: $Exports<'lattice/src/api/DataSourcesApi'>;
}
declare module 'lattice/src/api/EntityDataModelApi.js' {
  declare module.exports: $Exports<'lattice/src/api/EntityDataModelApi'>;
}
declare module 'lattice/src/api/LinkingApi.js' {
  declare module.exports: $Exports<'lattice/src/api/LinkingApi'>;
}
declare module 'lattice/src/api/OrganizationsApi.js' {
  declare module.exports: $Exports<'lattice/src/api/OrganizationsApi'>;
}
declare module 'lattice/src/api/PermissionsApi.js' {
  declare module.exports: $Exports<'lattice/src/api/PermissionsApi'>;
}
declare module 'lattice/src/api/PrincipalsApi.js' {
  declare module.exports: $Exports<'lattice/src/api/PrincipalsApi'>;
}
declare module 'lattice/src/api/RequestsApi.js' {
  declare module.exports: $Exports<'lattice/src/api/RequestsApi'>;
}
declare module 'lattice/src/api/SearchApi.js' {
  declare module.exports: $Exports<'lattice/src/api/SearchApi'>;
}
declare module 'lattice/src/api/SyncApi.js' {
  declare module.exports: $Exports<'lattice/src/api/SyncApi'>;
}
declare module 'lattice/src/config/Configuration.js' {
  declare module.exports: $Exports<'lattice/src/config/Configuration'>;
}
declare module 'lattice/src/constants/ApiNames.js' {
  declare module.exports: $Exports<'lattice/src/constants/ApiNames'>;
}
declare module 'lattice/src/constants/ApiPaths.js' {
  declare module.exports: $Exports<'lattice/src/constants/ApiPaths'>;
}
declare module 'lattice/src/constants/EnvToUrlMap.js' {
  declare module.exports: $Exports<'lattice/src/constants/EnvToUrlMap'>;
}
declare module 'lattice/src/constants/types/ActionTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/ActionTypes'>;
}
declare module 'lattice/src/constants/types/index.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/index'>;
}
declare module 'lattice/src/constants/types/PermissionTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/PermissionTypes'>;
}
declare module 'lattice/src/constants/types/PrincipalTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/PrincipalTypes'>;
}
declare module 'lattice/src/constants/types/RequestStateTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/RequestStateTypes'>;
}
declare module 'lattice/src/constants/types/SecurableTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/SecurableTypes'>;
}
declare module 'lattice/src/index.js' {
  declare module.exports: $Exports<'lattice/src/index'>;
}
declare module 'lattice/src/models/AccessCheck.js' {
  declare module.exports: $Exports<'lattice/src/models/AccessCheck'>;
}
declare module 'lattice/src/models/Ace.js' {
  declare module.exports: $Exports<'lattice/src/models/Ace'>;
}
declare module 'lattice/src/models/Acl.js' {
  declare module.exports: $Exports<'lattice/src/models/Acl'>;
}
declare module 'lattice/src/models/AclData.js' {
  declare module.exports: $Exports<'lattice/src/models/AclData'>;
}
declare module 'lattice/src/models/DataSource.js' {
  declare module.exports: $Exports<'lattice/src/models/DataSource'>;
}
declare module 'lattice/src/models/EntitySet.js' {
  declare module.exports: $Exports<'lattice/src/models/EntitySet'>;
}
declare module 'lattice/src/models/EntityType.js' {
  declare module.exports: $Exports<'lattice/src/models/EntityType'>;
}
declare module 'lattice/src/models/FullyQualifiedName.js' {
  declare module.exports: $Exports<'lattice/src/models/FullyQualifiedName'>;
}
declare module 'lattice/src/models/index.js' {
  declare module.exports: $Exports<'lattice/src/models/index'>;
}
declare module 'lattice/src/models/LinkingEntitySet.js' {
  declare module.exports: $Exports<'lattice/src/models/LinkingEntitySet'>;
}
declare module 'lattice/src/models/LinkingEntityType.js' {
  declare module.exports: $Exports<'lattice/src/models/LinkingEntityType'>;
}
declare module 'lattice/src/models/LinkingRequest.js' {
  declare module.exports: $Exports<'lattice/src/models/LinkingRequest'>;
}
declare module 'lattice/src/models/Organization.js' {
  declare module.exports: $Exports<'lattice/src/models/Organization'>;
}
declare module 'lattice/src/models/Principal.js' {
  declare module.exports: $Exports<'lattice/src/models/Principal'>;
}
declare module 'lattice/src/models/PropertyType.js' {
  declare module.exports: $Exports<'lattice/src/models/PropertyType'>;
}
declare module 'lattice/src/models/Request.js' {
  declare module.exports: $Exports<'lattice/src/models/Request'>;
}
declare module 'lattice/src/models/RequestStatus.js' {
  declare module.exports: $Exports<'lattice/src/models/RequestStatus'>;
}
declare module 'lattice/src/models/Role.js' {
  declare module.exports: $Exports<'lattice/src/models/Role'>;
}
declare module 'lattice/src/models/Schema.js' {
  declare module.exports: $Exports<'lattice/src/models/Schema'>;
}
declare module 'lattice/src/models/template.js' {
  declare module.exports: $Exports<'lattice/src/models/template'>;
}
declare module 'lattice/src/utils/AxiosUtils.js' {
  declare module.exports: $Exports<'lattice/src/utils/AxiosUtils'>;
}
declare module 'lattice/src/utils/LangUtils.js' {
  declare module.exports: $Exports<'lattice/src/utils/LangUtils'>;
}
declare module 'lattice/src/utils/Logger.js' {
  declare module.exports: $Exports<'lattice/src/utils/Logger'>;
}
declare module 'lattice/src/utils/ValidationUtils.js' {
  declare module.exports: $Exports<'lattice/src/utils/ValidationUtils'>;
}
