// flow-typed signature: 2ef9328080bb8821d002ce4761459aaa
// flow-typed version: <<STUB>>/lattice-ui-kit_v0.42.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice-ui-kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice-ui-kit' {
  declare module.exports: any;
}
