export const actionType = {
  UPDATE_ACTIVE_ITEM: 'UPDATE_ACTIVE_ITEM',
  UPDATE_LIST: 'UPDATE_LIST',
  START_FETCH_PROPERTY_DATA: 'START_FETCH_PROPERTY_DATA',
  LOADED_FETCH_PROPERTY_DATA: 'LOADED_FETCH_PROPERTY_DATA',
  START_FETCH_ENTITY_DATA: 'START_FETCH_ENTITY_DATA',
  LOADED_FETCH_ENTITY_DATA: 'LOADED_FETCH_ENTITY_DATA',
  START_FETCH_ASSOCIATION_DATA: 'START_FETCH_ASSOCIATION_DATA',
  LOADED_FETCH_ASSOCIATION_DATA: 'LOADED_FETCH_ASSOCIATION_DATA'
};

