export const actionType = {
  UPDATE_ACTIVE_ITEM: 'UPDATE_ACTIVE_ITEM',
  UPDATE_LIST: 'UPDATE_LIST',
  START_FETCH_PROPERTY_DATA: 'START_FETCH_PROPERTY_DATA',
  FINISHED_FETCH_PROPERTY_DATA: 'FINISHED_FETCH_PROPERTY_DATA',
  START_FETCH_ENTITY_DATA: 'START_FETCH_ENTITY_DATA',
  FINISHED_FETCH_ENTITY_DATA: 'FINISHED_FETCH_ENTITY_DATA',
  START_FETCH_ASSOCIATION_DATA: 'START_FETCH_ASSOCIATION_DATA',
  FINISHED_FETCH_ASSOCIATION_DATA: 'FINISHED_FETCH_ASSOCIATION_DATA'
};

export const colors = {
  SELECTED: 'linear-gradient(to left, rgba(186,95,158,.4) , rgba(59,149,212,.4))',
  TRANSPARENT: 'transparent',
  HOVER: '#F1DFEB',
  BACKGROUND: '#fefefe',
  BORDERS: '1px solid #3FA3F8',
  SLECTED_TEXT: '#5537DA',
  BUTTON_BACKGROUND: '#ED66B1',
  BASE_TEXT: '#090825',
  BAR: '#EEEEF8'
};

